site_url: https://thedeetees.co.uk
display_url: https://thedeetees.co.uk
backend:
  name: git-gateway # test-repo https://www.netlifycms.org/docs/git-gateway-backend/
  branch: main
local_backend: false # https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
publish_mode: editorial_workflow
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "pages/content/home.json"
        editor:
          preview: false
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "post"
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "show"
    label: "Show"
    folder: "shows"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{venue}}"
    editor:
      preview: false
    fields:
      - { label: "Venue", name: "venue", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
